tomcat:
  uri-encoding: utf-8
server:
  port: 8089
spring:
  datasource:
    name: ORCL
    url: jdbc:oracle:thin:@47.92.129.99:1600:ORCL
    username: XZXT
    password: XZXT
    driver-class-name: oracle.jdbc.driver.OracleDriver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ye.functiondemo.model
